{{- if ((.Values.security).networkPolicy).enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "postgres-cnpg.fullname" . }}
spec:
  podSelector:
    matchLabels:
        cnpg.io/cluster: {{ .Chart.Name }}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
