apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cnpg.fullname" . }}-user
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.auth.username | default ".Values.auth.username"  | b64enc | quote }}
  password: {{ .Values.auth.password | default ".Values.auth.password"  | b64enc | quote }}
