apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cnpg.fullname" . }}-superuser
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM=
  password: {{ .Values.auth.password | default ".Values.auth.password"  | b64enc | quote }}
