kafka:
  fullnameOverride: kafka
  replicaCount: 3
  zookeeper:
    fullnameOverride: kafka-zookeeper
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT

fullnameOverride: kafka

discovery:
  enabled: true
